name: Build and test

on: push
jobs:


#   build:
#     name: Build
#     runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Test
#       run: make test
    # - name: Run Instrumentation Tests
    #   uses: reactivecircus/android-emulator-runner@v2
    #   with:
    #     cmd: ./gradlew connectedUnbrandedWebviewDebugAndroidTest --stacktrace
    #     api: 30
    #     tag: default
    #     abi: arm64-v8a
    #   - name: Set up ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.6
    # - name: Set up fastlane
    #   run: gem install fastlane --no-document --quiet
    # - name: Unpack secrets
    #   env:
    #     ANDROID_SECRETS_KEY: ${{ secrets.ANDROID_SECRETS_KEY }}
    #     ANDROID_SECRETS_IV: ${{ secrets.ANDROID_SECRETS_IV }}
    #   run: |
    #     openssl aes-256-cbc -K $ANDROID_SECRETS_KEY -iv $ANDROID_SECRETS_IV -in secrets.tar.gz.enc -out ./secrets.tar.gz -d
    #     tar -xf ./secrets.tar.gz
    # - name: Assemble unbranded
    #   uses: maierj/fastlane-action@v1.4.0
    #   env:
    #     ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
    #     ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    #     ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
    #     ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    #   with:
    #     lane: build
    #     options: '{ "flavor": "unbranded" }'                    
  # instrumentation:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@master
  #       with:
  #           project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
  #           service_account_key: ${{ secrets.GCLOUD_AUTH }}
  #           export_default_credentials: true

      # - name: Use gcloud CLI
      #   run: gcloud info
      # # Check out the repository
      # - uses: actions/checkout@v2

      # # Run the Firebase Test Lab Action
      # - name: Run tests on Firebase Test Lab
      #   uses: asadmansr/Firebase-Test-Lab-Action@v1.0
      #   with:
      #     arg-spec: 'tests.yml:android'
      #   env:
      #     SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        ndk: 21.4.7075529
        script: ./gradlew connectedUnbrandedWebviewDebug
  # apk:
  #   name: Generate APK
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8

      # - name: Assemble app debug APK
      #   run: bash ./gradlew assembleUnbrandedWebviewDebug --stacktrace
        # env:
        #   ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
        #   ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        #   ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        #   ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      # - name: Upload app APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-debug
      #     path: build/outputs/apk/unbrandedWebview/debug/medic-android-SNAPSHOT-unbranded-webview-armeabi-v7a-debug.apk

      # - name: Assemble Android Instrumentation Tests
      #   run: bash ./gradlew assembleUnbrandedWebviewDebugAndroidTest
      #   # env:
      #   #   ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
      #   #   ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #   #   ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      #   #   ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      # - name: Upload Android Test APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-debug-androidTest
      #     path: build/outputs/apk/androidTest/unbrandedWebview/debug/medic-android-SNAPSHOT-unbranded-webview-debug-androidTest.apk

  # firebase:
  #   name: Run UI tests with Firebase Test Lab
  #   needs: apk
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Download app APK
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: app-debug

  #     - name: Download Android test APK
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: app-debug-androidTest

  #     - name: Login to Google Cloud
  #       uses: GoogleCloudPlatform/google-github-actions/setup-gcloud
  #       with:
          
  #         service_account_key: ${{ secrets.GCLOUD_AUTH }}

  #     - name: Set current project
  #       run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

  #     - name: Run Instrumentation Tests in Firebase Test Lab
  #       run: gcloud firebase test android run --type instrumentation --app app-debug/medic-android-SNAPSHOT-unbranded-webview-armeabi-v7a-debug.apk --test app-debug-androidTest/medic-android-SNAPSHOT-unbranded-webview-debug-androidTest.apk --device model=Pixel2,version=29,locale=pl,orientation=portrait