name: Test 

on: push
jobs:
  test-mac:
    runs-on: macos-latest
#     strategy:
#       matrix:
#         api-level: [29, 30]
#         target: [default, google_apis]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run tests on Unbranded
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23  #${{ matrix.api-level }}
        #target: ${{ matrix.target }}
        script: ./gradlew connectedUnbrandedWebviewDebugAndroidTest -Pabi=x86 --stacktrace
    - name: run tests on gamma
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23
        script: ./gradlew connectedMedicmobilegammaWebviewDebugAndroidTest -Pabi=x86